const homeUrl = "/admin";
const allUser = ["agent", "super-agent", "administrator"];

export const sidebarData = [
    {
        id: "menu-1",
        title: "Statistics",
        icon: <i className="fal fa-chart-bar"></i>,
        link: `${homeUrl}/dashboard`,
        key: "Statistics",
        userAccess: allUser,
    },
    {
        id: "menu-2",
        title: "Users",
        icon: <i className="fal fa-users-cog"></i>,
        link: `${homeUrl}/users`,
        key: "user",
        userAccess: allUser,
    },
    {
        id: "menu-3",
        title: "Global Reports",
        icon: <i className="fal fa-globe"></i>,
        link: { javascript: void 0 },
        key: "global_reports",
        userAccess: allUser,
        child: [
            {
                id: "menu-3.1",
                title: "Report by Agent",
                icon: <i className="fal fa-user-secret"></i>,
                link: `${homeUrl}/agent-report`,
                parentId: "menu-3",
                key: "report_by_agent",
                userAccess: allUser,
            },
            {
                id: "menu-3.2",
                title: "Report by Player",
                icon: <i className="fal fa-user-cowboy"></i>,
                link: `${homeUrl}/player-report`,
                parentId: "menu-3",
                key: "report_by_player",
                userAccess: allUser,
            },
        ],
    },
    {
        id: "menu-4",
        title: "Credits Reports",
        icon: <i className="fal fa-file-alt"></i>,
        link: { javascript: void 0 },
        key: "credits_reports",
        userAccess: ["super-agent", "administrator"],
        child: [
            {
                id: "menu-4.1",
                title: "Sales Details",
                icon: <i className="fal fa-user-secret"></i>,
                link: `${homeUrl}/charges-and-withdrawals`,
                parentId: "menu-4",
                key: "sales_details",
                userAccess: ["super-agent", "administrator"],
            },
            {
                id: "menu-4.2",
                title: "Player History",
                icon: <i className="fal fa-user-cowboy"></i>,
                link: `${homeUrl}/player-history`,
                parentId: "menu-4",
                key: "player_history",
                userAccess: ["super-agent", "administrator"],
            },
        ],
    },
    {
        id: "menu-5",
        title: "Game Reports",
        icon: <i className="fal fa-gamepad-alt"></i>,
        link: { javascript: void 0 },
        key: "game_report",
        userAccess: ["super-agent", "administrator"],
        child: [
            {
                id: "menu-5.1",
                title: "Casino",
                icon: <i className="fal fa-user-secret"></i>,
                link: `${homeUrl}/casino-game-reports`,
                parentId: "menu-5",
                key: "casino",
                userAccess: ["super-agent", "administrator"],
            },
            {
                id: "menu-5.2",
                title: "Sports",
                icon: <i className="fal fa-user-cowboy"></i>,
                link: `${homeUrl}/sports-game-reports`,
                parentId: "menu-5",
                key: "sports",
                userAccess: ["super-agent", "administrator"],
            },
            {
                id: "menu-5.3",
                title: "Poker",
                icon: <i className="fal fa-user-cowboy"></i>,
                link: `${homeUrl}/poker-game-reports`,
                parentId: "menu-5",
                key: "poker",
                userAccess: ["super-agent", "administrator"],
            },
        ],
    },
    {
        id: "menu-6",
        title: "Finance",
        icon: <i className="fal fa-sack-dollar"></i>,
        link: { javascript: void 0 },
        key: "finance",
        userAccess: ["super-agent", "administrator"],
        child: [
            {
                id: "menu-6.1",
                title: "Agents",
                icon: <i className="fal fa-user-secret"></i>,
                link: { javascript: void 0 },
                parentId: "menu-6",
                key: "agents",
                userAccess: ["super-agent", "administrator"],
                subChild: [
                    {
                        id: "menu-6.1.1",
                        title: "Operations",
                        icon: <i className="fal fa-user-secret"></i>,
                        link: `${homeUrl}/finance-agent-operation`,
                        parentId: "menu-6.1",
                        key: "agents_operations",
                        userAccess: ["super-agent", "administrator"],
                    },
                    {
                        id: "menu-6.1.2",
                        title: "Balances",
                        icon: <i className="fal fa-user-cowboy"></i>,
                        link: `${homeUrl}/finance-agent-balances`,
                        parentId: "menu-6.1",
                        key: "agents_balances",
                        userAccess: ["super-agent", "administrator"],
                    },
                ],
            },
            {
                id: "menu-6.2",
                title: "Players",
                icon: <i className="fal fa-user-cowboy"></i>,
                link: { javascript: void 0 },
                key: "players",
                userAccess: ["super-agent", "administrator"],
                subChild: [
                    {
                        id: "menu-6.2.1",
                        title: "Operations",
                        icon: <i className="fal fa-user-secret"></i>,
                        link: `${homeUrl}/finance-players-operation`,
                        parentId: "menu-6.2",
                        key: "players_operations",
                        userAccess: ["super-agent", "administrator"],
                    },
                    {
                        id: "menu-6.2.2",
                        title: "Balances",
                        icon: <i className="fal fa-user-cowboy"></i>,
                        link: `${homeUrl}/finance-player-balances`,
                        parentId: "menu-6.2",
                        key: "players_balances",
                        userAccess: ["super-agent", "administrator"],
                    },
                    {
                        id: "menu-6.2.3",
                        title: "Withdrawal Request",
                        icon: <i className="far fa-wallet"></i>,
                        link: `${homeUrl}/finance-players-withdrawal-request`,
                        parentId: "menu-6.2",
                        key: "withdrawal_request",
                        userAccess: ["super-agent", "administrator"],
                    },
                ],
            },
        ],
    },
    {
        id: "menu-7",
        title: "My Summary",
        icon: <i className="fal fa-file-invoice-dollar"></i>,
        link: `${homeUrl}/my-summary`,
        key: "my_summary",
        userAccess: allUser,
    },
    {
        id: "menu-8",
        title: "Deposits",
        icon: <i className="far fa-plus-circle"></i>,
        link: `${homeUrl}/deposits`,
        key: "deposits",
        userAccess: ["administrator"],
    },
    {
        id: "menu-9",
        title: "Wallet Address",
        icon: <i className="far fa-plus-circle"></i>,
        link: `${homeUrl}/wallet-address`,
        key: "wallet_address",
        userAccess: ["administrator"],
    },
    {
        id: "menu-10",
        title: "Translations",
        icon: <i className="fal fa-language"></i>,
        link: `${homeUrl}/translate-site`,
        key: "translations",
        userAccess: ["administrator"],
    },
    {
        id: "menu-11",
        title: "Store",
        icon: <i className="fal fa-store"></i>,
        link: { javascript: void 0 },
        key: "store",
        userAccess: ["administrator"],
        child: [
            {
                id: "menu-11.1",
                title: "Rewards",
                icon: <i className="fal fa-treasure-chest"></i>,
                link: { javascript: void 0 },
                parentId: "menu-11",
                key: "store_rewards",
                userAccess: ["administrator"],
                subChild: [
                    {
                        id: "menu-11.1.1",
                        title: "Create",
                        icon: <i className="fal fa-plus-circle"></i>,
                        link: `${homeUrl}/store/rewards/create`,
                        parentId: "menu-11.1",
                        key: "store_rewards_create",
                        userAccess: ["administrator"],
                    },
                    {
                        id: "menu-11.1.2",
                        title: "List",
                        icon: <i className="fal fa-list"></i>,
                        link: `${homeUrl}/store/rewards`,
                        parentId: "menu-11.1",
                        key: "store_rewards_list",
                        userAccess: ["administrator"],
                    },
                ],
            },
            {
                id: "menu-11.2",
                title: "Reports",
                icon: <i className="fal fa-treasure-chest"></i>,
                link: { javascript: void 0 },
                parentId: "menu-11",
                key: "store_reports",
                userAccess: ["administrator"],
                subChild: [
                    {
                        id: "menu-11.2.1",
                        title: "Redeemed Rewards",
                        icon: <i className="fal fa-sort-alt"></i>,
                        link: `${homeUrl}/store/rewards/redeemed-rewards`,
                        parentId: "menu-11.2",
                        key: "store_reports_redeemed_rewards",
                        userAccess: ["administrator"],
                    },
                    {
                        id: "menu-11.2.2",
                        title: "Points Totals",
                        icon: <i className="fal fa-sort-alt"></i>,
                        link: `${homeUrl}/store/rewards/points-totals`,
                        parentId: "menu-11.2",
                        key: "store_reports_points_total",
                        userAccess: ["administrator"],
                    },
                    {
                        id: "menu-11.2.3",
                        title: "Store Balances",
                        icon: <i className="fal fa-coins"></i>,
                        link: `${homeUrl}/store/rewards/store-balances`,
                        parentId: "menu-11.2",
                        key: "store_reports_store_balances",
                        userAccess: ["administrator"],
                    },
                ],
            },
        ],
    },
    {
        id: "menu-12",
        title: "Sliders",
        icon: <i className="fal fa-sliders-h"></i>,
        link: { javascript: void 0 },
        key: "sliders",
        userAccess: ["administrator"],
        child: [
            {
                id: "menu-12.1",
                title: "Banner Slider",
                icon: <i className="fal fa-border-top"></i>,
                link: `${homeUrl}/banner-sliders`,
                parentId: "menu-12",
                key: "banner_slider",
                userAccess: ["administrator"],
            },
            {
                id: "menu-12.2",
                title: "Offer Slider",
                icon: <i className="fal fa-badge-percent"></i>,
                link: `${homeUrl}/offer-sliders`,
                parentId: "menu-12",
                key: "offer_slider",
                userAccess: ["administrator"],
            },
            {
                id: "menu-12.3",
                title: "Featured Games Slider",
                icon: <i className="fal fa-border-bottom"></i>,
                link: `${homeUrl}/featured-games-slider`,
                parentId: "menu-12",
                key: "featured_games_slider",
                userAccess: ["administrator"],
            },
        ],
    },
    {
        id: "menu-13",
        title: "Sports Book Settings",
        icon: <i className="far fa-futbol"></i>,
        link: `${homeUrl}/sports-book-settings`,
        key: "sports_book_settings",
        userAccess: ["administrator"],
    },
    {
        id: "menu-14",
        title: "Bonus System",
        icon: <i className="far fa-sack-dollar"></i>,
        link: { javascript: void 0 },
        key: "bonus_system",
        userAccess: ["administrator"],
        child: [
            {
                id: "menu-14.1",
                title: "Campaigns",
                icon: <i className="far fa-trophy-alt"></i>,
                link: { javascript: void 0 },
                key: "bonus_system_campaigns",
                userAccess: ["administrator"],
                subChild: [
                    {
                        id: "menu-14.1.1",
                        title: "New",
                        icon: <i className="fal fa-plus-circle"></i>,
                        link: "/admin/bonus-system/campaigns/create",
                        key: "bonus_system_campaigns_new",
                        userAccess: ["administrator"],
                    },
                    {
                        id: "menu-14.1.2",
                        title: "List",
                        icon: <i className="fal fa-list"></i>,
                        link: "/admin/bonus-system/campaigns",
                        key: "bonus_system_campaigns_list",
                        userAccess: ["administrator"],
                    },
                ],
            },
            // {
            //     id: "menu-14.2",
            //     title: "Reports",
            //     icon: <i className="far fa-file-chart-line"></i>,
            //     link: { javascript: void 0 },
            //     key: "bonus_system_reports",
            //     userAccess: ['administrator'],
            //     subChild: [
            //         {
            //             id: "menu-14.2.1",
            //             title: "Campaigns overview",
            //             icon: <i className="far fa-eye"></i>,
            //             link: "/admin/bonus-system/campaigns/reports/campaigns-overview",
            //             key: "bonus_system_reports_campaign_overview",
            //             userAccess: ['administrator']
            //         },
            //         {
            //             id: "menu-14.2.2",
            //             title: "Campaigns by user",
            //             icon: <i className="far fa-user-tie"></i>,
            //             link: "/admin/bonus-system/campaigns/reports/participation-by-users",
            //             key: "bonus_system_reports_campaigns_by_user",
            //             userAccess: ['administrator']
            //         },
            //     ],
            // }
        ],
    },
    {
        id: "menu-15",
        title: "Settings",
        icon: <i className="far fa-cog"></i>,
        link: `${homeUrl}/settings`,
        key: "settings",
        userAccess: ["administrator"],
    },
    {
        id: "menu-16",
        title: "Posts",
        icon: <i className="far fa-copy"></i>,
        link: { javascript: void 0 },
        key: "posts",
        userAccess: ["administrator"],
        child: [
            {
                id: "menu-16.1",
                title: "New",
                icon: <i className="far fa-file-plus"></i>,
                link: `${homeUrl}/posts/new`,
                parentId: "menu-16",
                key: "posts_new",
                userAccess: ["administrator"],
            },
            {
                id: "menu-16.2",
                title: "Posts",
                icon: <i className="fal fa-list-alt"></i>,
                link: `${homeUrl}/posts`,
                parentId: "menu-16",
                key: "posts_posts",
                userAccess: ["administrator"],
            },
            {
                id: "menu-16.3",
                title: "Categories",
                icon: <i className="far fa-poll-h"></i>,
                link: `${homeUrl}/posts/categories`,
                parentId: "menu-16",
                key: "posts_categories",
                userAccess: ["administrator"],
            },
        ],
    },
];
